settings:
  name: Cloud Volumes ONTAP release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true  
  versions:
    - version-number: "9.14.0"
      url: /cloud-volumes-ontap-relnotes
    - version-number: "9.13.1"
      url: /cloud-volumes-ontap-9131-relnotes
    - version-number: "9.13.0"
      url: /cloud-volumes-ontap-9130-relnotes
    - version-number: "9.12.1"
      url: /cloud-volumes-ontap-9121-relnotes
    - version-number: "9.12.0"
      url: /cloud-volumes-ontap-9120-relnotes
    - version-number: "9.11.1"
      url: /cloud-volumes-ontap-9111-relnotes
    - version-number: "9.11.0"
      url: /cloud-volumes-ontap-9110-relnotes
    - version-number: "9.10.1"
      url: /cloud-volumes-ontap-9101-relnotes
    - version-number: "9.10.0"
      url: /cloud-volumes-ontap-9100-relnotes
    - version-number: "9.9.1"
      url: /cloud-volumes-ontap-991-relnotes
    - version-number: "9.9.0"
      url: /cloud-volumes-ontap-990-relnotes
    - version-number: "9.8"
      url: /cloud-volumes-ontap-98-relnotes
    - version-number: "9.7"
      url: /cloud-volumes-ontap-97-relnotes
    - version-number: "9.6"
      url: /cloud-volumes-ontap-96-relnotes
    - version-number: "9.5"
      url: /cloud-volumes-ontap-95-relnotes
    - version-number: "9.4"
      url: /cloud-volumes-ontap-94-relnotes
    - version-number: "9.3"
      url: /cloud-volumes-ontap-93-relnotes
sidebar:
  entries:
    - title: Release notes home
      url: /index.html
    - title: What's new
      url: /reference-new.html
    - title: Licensing overview
      url: /concept-licensing.html
    - title: Supported configurations
      entries:
        - title: AWS
          url: /reference-configs-aws.html
        - title: Azure
          url: /reference-configs-azure.html
        - title: Google Cloud
          url: /reference-configs-gcp.html
    - title: Storage limits
      entries:
        - title: AWS
          url: /reference-limits-aws.html
        - title: Azure
          url: /reference-limits-azure.html
        - title: Google Cloud
          url: /reference-limits-gcp.html
    - title: Known issues
      url: /reference-issues.html
    - title: Known limitations
      entries:
        - title: Common limitations
          url: /reference-limitations.html
        - title: Limitations in AWS
          url: /reference-limitations-aws.html
        - title: Limitations in Azure
          url: /reference-limitations-azure.html
        - title: Limitations in Google Cloud
          url: /reference-limitations-gcp.html
    - title: Cloud provider integrations
      url: /reference-provider-integrations.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
homepage:
  tiles:
    - title: Get started
      links:
        - title: What's new
          url: reference-new.html
        - title: Licensing overview
          url: concept-licensing.html
    - title: Amazon Web Services
      links:
        - title: Supported configurations
          url: reference-configs-aws.html
        - title: Storage limits
          url: reference-limits-aws.html
        - title: Limitations
          url: reference-limitations-aws.html
    - title: Google Cloud
      links:
        - title: Supported configurations
          url: reference-configs-gcp.html
        - title: Storage limits
          url: reference-limits-gcp.html
        - title: Limitations
          url: reference-limitations-gcp.html
    - title: Microsoft Azure
      links:
        - title: Supported configurations
          url: reference-configs-azure.html
        - title: Storage limits
          url: reference-limits-azure.html
        - title: Limitations
          url: reference-limitations-azure.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: BlueXP blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events

