---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.15.1 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.15.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.15.1 includes new enhancements.

Additional features and enhancements are also introduced in the latest versions of BlueXP. See the https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html[BlueXP Release Notes^] for details.

== 9.15.1 GA (22 August 2024)
The Cloud Volumes ONTAP 9.15.1 GA is now available in AWS, Azure, and Google Cloud. The GA version is available for deployment and upgrade. This release includes the following new features and enhancements.

//Update this section for every major release and every patch. This section has P1 for this version as the patch is the first major rls avl for deployment and upgrade. Other patches might top this one. When 9.x.1 version of a 9.x.0 version is available, the patch rls for 9.x.0 stops: MM.

=== ##Support for Premium SSD v2 Managed Disks##
Premium SSD v2 Managed Disks are now supported in Cloud Volumes ONTAP. These premium disks provide higher performance with lower latency at a lower cost for both single node and high-availability (HA) pairs, as compared to Premium SSD Shared Managed Disks. Like other managed disks, the maximum disk size is 32 TiB. The performance (capacity, throughput, and IOPS) of a Premium SSD v2 Managed Disks can be configured, allowing workloads to be cost effective, while meeting shifting performance needs.
CVO 9.15.1 in Azure leverages Virtual Machines Scale Sets in Flexible orchestration mode for deploying virtual machine (VM) instances in single availability zones for high-availability (HA) pairs. This deployment mode, by default, makes use of Premium SSD v2 Managed Disks.

For information, refer to https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-storage.html#azure-storage[Azure storage^].

=== ##Azure HA deployments supported in single availability zones##
Beginning with Cloud Volumes ONTAP 9.15.1, you can deploy virtual machine (VM) instances in single availability zones (AZs) in HA mode. Unlike the previous non-zonal deployments, Cloud Volumes ONTAP 9.15.1 uses Microsoft Virtual Machines Scale Sets in Flexible orchestration mode to deploy all resources, including separate fault domains within the same AZ, guaranteeing optimal availability. This deployment covers all flavors of the HA mode, Pageblob, locally-redundant storage (LRS), zone-redundant storage (ZRS) or multi-zonal, and LRS zonal (single AZ), when the following criteria are met: 

* The version of Cloud Volumes ONTAP is 9.15.1 or later.
* The region supports Virtual Machines Scale Sets in Flexible orchestration mode. For information about the supported regions, refer to https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/[Microsoft Azure website: Products available by region^].
* The selected zone in a region supports Virtual Machines Scale Sets in Flexible orchestration mode.
* The subscription is registered for the `Microsoft.Compute/VMOrchestratorZonalMultiFD` feature.
+
For more information, refer to https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-otc-azure.html#launching-a-cloud-volumes-ontap-ha-pair-in-azure[Launching a Cloud Volumes ONTAP HA pair in Azure^] and https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-saz-feature.html[Enable VMOrchestratorZonalMultiFD for single availability zones^].

If any of these criteria is not fulfilled, the previous LRS non-zonal deployment becomes effective.


== Upgrade notes.

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from BlueXP. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when BlueXP notifies you^].

=== Supported upgrade path

You can upgrade to Cloud Volumes ONTAP 9.15.1 from 9.15.0 and 9.14.1 releases. BlueXP will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.

//Update this version for every major release. 9.x.0 v is can be usually upgraded from only the prev 9.x.1 version. Connector version removed as per code separation verification from engg: MM

=== Downtime

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

=== c4, m4, and r4 instances no longer supported

In AWS, the c4, m4, and r4 EC2 instance types are no longer supported with Cloud Volumes ONTAP. If you have an existing system that's running on a c4, m4, or r4 instance type, you must change to an instance type in the c5, m5, or r5 instance family. You can't upgrade to this release until you change the instance type.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html[Learn how to change the EC2 instance type for Cloud Volumes ONTAP^].

Refer to link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html[NetApp Support^] to learn more about the end of availability and support for these instance types. 