---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.16.1 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.16.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.16.1 includes new enhancements.

Additional features and enhancements are also introduced in the latest versions of BlueXP. See the https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html[BlueXP Release Notes^] for details.

//== 9.16.1 P4 ( 2025)
//The 9.16.1 P4 patch can now be deployed and upgraded for Cloud Volumes ONTAP in AWS, Azure, and Google Cloud. BlueXP will prompt you to upgrade your existing systems to this patch release. 

//[NOTE]
//Cloud Volumes ONTAP 9.16.1 in AWS is available in this and later patch versions only, not the earlier ones.

//link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P4[View the list of bugs fixed in the P4 patch^] (NetApp Support Site login required).

== 9.16.1 P3 (29 May 2025)
The 9.16.1 P3 patch can now be deployed and upgraded for Cloud Volumes ONTAP in Azure and Google Cloud. However, this version is unavailable for deployment and upgrade in AWS. BlueXP will prompt you to upgrade your existing systems to this patch release.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P3[View the list of bugs fixed in the P3 patch^] (NetApp Support Site login required).


== 9.16.1 P2 (17 April 2025)
The 9.16.1 P2 patch can now be deployed and upgraded for Cloud Volumes ONTAP in Azure and Google Cloud. However, this version is unavailable for deployment and upgrade in AWS. BlueXP will prompt you to upgrade your existing systems to this patch release.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P2[View the list of bugs fixed in the P2 patch^] (NetApp Support Site login required).

== 9.16.1 P1 (17 April 2025)
The 9.16.1 P1 patch can now be deployed and upgraded for Cloud Volumes ONTAP in Azure and Google Cloud. However, this version is unavailable for deployment and upgrade in AWS. BlueXP will prompt you to upgrade your existing systems to this patch release.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P1[View the list of bugs fixed in the P1 patch^] (NetApp Support Site login required).

== 9.16.1 GA (6 March 2025)
You can now use the Cloud Volumes ONTAP 9.16.1 General Availability release for deployment and upgrade in Azure and Google Cloud. However, this version is unavailable for deployment and upgrade in AWS.

//Update this section for every major release and every patch. This section can have a patch version as the first major release available for deployment and upgrade. Other patches might top this one. When 9.x.1 version of a 9.x.0 version is available, the patch rls for 9.x.0 stops: MM


== Upgrade notes

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from BlueXP. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when BlueXP notifies you^].

=== Supported upgrade path
You can upgrade to Cloud Volumes ONTAP 9.16.1 GA from the 9.15.1 release in Azure and Google Cloud. BlueXP will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.

[NOTE]
For AWS, you won't be prompted for this upgrade. Upgrading to Cloud Volumes ONTAP 9.16.1 GA is not supported in AWS.

//Update this version for every major release. 9.x.0 v is can be usually upgraded from only the prev 9.x.1 version. But if the 9.x.0 version for a release has not gone, the n-2 for 9.x.1 will not be continued, and in that case only the previous 9.x.1 will be the upgrade path. Connector version removed as per code separation verification from engg: MM

=== Downtime

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is non-disruptive and I/O is uninterrupted. During this non-disruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

