---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.14.0 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.14.0 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.14.0 includes new enhancements.

Additional features and enhancements are also introduced in the latest versions of BlueXP. See the https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html[BlueXP Release Notes^] for details.

== 9.14.0 P1 (10 November 2023)
The 9.14.0 P1 patch is now available for Cloud Volumes ONTAP for all cloud providers if you have a Connector running version 3.9.27 or later. BlueXP will prompt you to upgrade your existing systems to this patch release.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.0P1[View the list of bugs fixed in the P6 patch^] (NetApp Support Site login required).

== 9.14.0 (29 September 2023)
The General Availability (GA) release of Cloud Volumes ONTAP 9.14.0 is now available in AWS, Azure, and Google Cloud. This release includes the following new features and enhancements.

=== SnapMirror traffic segregation in Azure
You can now segregate SnapMirror replication traffic from data and management traffic. This new feature allows you to segregate SnapMirror replication traffic by leveraging an additional subnet that isn't routable to the existing subnet used for data and management traffic. 

Learn more about how to link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-segregate-snapmirror-azure.html[segregate SnapMirror traffic in Azure^].

== Upgrade notes

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from BlueXP. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when BlueXP notifies you^].

=== Supported upgrade path

You can upgrade to Cloud Volumes ONTAP 9.14.0 from the 9.13.1 release. BlueXP will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.

=== Required version of the Connector

The BlueXP Connector must be running version 3.9.27 or later to deploy new Cloud Volumes ONTAP 9.14.0 systems and to upgrade existing systems to 9.14.0.

TIP: Automatic upgrades of the Connector are enabled by default so you should be running the latest version.

=== Downtime

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

=== c4, m4, and r4 instances no longer supported

In AWS, the c4, m4, and r4 EC2 instance types are no longer supported with Cloud Volumes ONTAP. If you have an existing system that's running on a c4, m4, or r4 instance type, you must change to an instance type in the c5, m5, or r5 instance family. You can't upgrade to this release until you change the instance type.
 
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html[Learn how to change the EC2 instance type for Cloud Volumes ONTAP^].

Refer to link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html[NetApp Support^] to learn more about the end of availability and support for these instance types. 
