---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.18.1 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.18.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can now deploy and upgrade to Cloud Volumes ONTAP 9.18.1. You can see the base version of this release and the latest patch version available for deployment and upgrade in the Console.

To know about the Cloud Volumes ONTAP features that are introduced in the latest versions of the NetApp Console, see what's new in https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html[Cloud Volumes ONTAP^].

//== 9.18.1 P1 (2026)
//The Cloud Volumes ONTAP 9.18.1 P1 patch is now available for deployment and upgrade in AWS, Azure, and Google Cloud. The Console will prompt you to upgrade your existing systems to this patch release.

//link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.18.1P1[View the list of bugs fixed in the P1 patch^] (NetApp Support Site login required).

== 9.18.1 GA (10 February 2026)
The Cloud Volumes ONTAP 9.18.1 General Availability release is now available for deployment and upgrade in Amazon Web Services (AWS) and Microsoft Azure. This version is not available for deployment and upgrade in Google Cloud. 

//Update this section for every major release and every patch. This section can have a patch version as the first major release available for deployment and upgrade. Other patches might top this one. When 9.x.1 version of a 9.x.0 version is available, the patch rls for 9.x.0 stops: MM



== Upgrade notes

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from the Console. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when the Console notifies you^].

=== Supported upgrade path
You can upgrade to Cloud Volumes ONTAP 9.18.1 from the 9.17.1 P1 and later patches in AWS and Azure. The Console will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.

[NOTE]
Cloud Volumes ONTAP 9.18.1 is not available for upgrade in Google Cloud.

//Update this version for every major release. 9.x.0 v is can be usually upgraded from only the prev 9.x.1 version. But if the 9.x.0 version for a release has not gone, the n-2 for 9.x.1 will not be continued, and in that case only the previous 9.x.1 will be the upgrade path. The Console agent version removed as per code separation verification from engg: MM

=== Downtime

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is non-disruptive and I/O is uninterrupted. During this non-disruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

