---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.19.1 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.19.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can now deploy and upgrade to Cloud Volumes ONTAP 9.19.1. You can see the base version of this release and the latest patch versions available for deployment and upgrade in the Console.

To know about more Cloud Volumes ONTAP features, supported configurations, limits, and more, see https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/index.html[Cloud Volumes ONTAP documentation^].

== 9.19.1 RC (13 July 2026)
The Cloud Volumes ONTAP 9.19.1 Release Candidate (RC) is now available for deployment and upgrade in Google Cloud only. This version is unavailable for deployment and upgrade in Amazon Web Services (AWS) and Microsoft Azure (Azure).

//Update this section for every major release and every patch. This section can have a patch version as the first major release available for deployment and upgrade. Other patches might top this one. When 9.x.1 version of a 9.x.0 version is available, the patch rls for 9.x.0 stops: MM

== Upgrade notes

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from the Console. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when the Console notifies you^].

=== Supported upgrade path
You can upgrade to Cloud Volumes ONTAP 9.19.1 RC from 9.18.1 in only Google Cloud. The Console will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.

[NOTE]
In AWS and Azure, you won't be prompted for an upgrade to 9.19.1 RC because this version is unavailable for deployment and upgrade for these cloud providers.

//Update this version for every major release. 9.x.0 v is can be usually upgraded from only the prev 9.x.1 version. But if the 9.x.0 version for a release has not gone, the n-2 for 9.x.1 will not be continued, and in that case only the previous 9.x.1 will be the upgrade path. The Console agent version removed as per code separation verification from engg: MM

=== Downtime

* The upgrade of a single-node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is non-disruptive and I/O is uninterrupted. During this non-disruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

//Update on 22 July, 2026: There were many more topics in the previous versions. But as part of the the restructuring activity of the CVO docs, they have been moved to the core docs. The redirected topics are listed in the store-redirects folder: MM
