---
sidebar: sidebar
permalink: reference-limitations-azure.html
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache
summary: These known limitations are specific to Cloud Volumes ONTAP in Microsoft Azure.
---

= Known limitations for Cloud Volumes ONTAP in Azure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following known limitations are specific to Cloud Volumes ONTAP in Microsoft Azure. Be sure to also review link:reference-limitations.html[Limitations for Cloud Volumes ONTAP in all cloud providers].

== Limitations with using Azure VM extensions
Cloud Volumes ONTAP does not support Azure virtual machine (VM) extensions and VM applications in a deployment. Using Cloud Volumes ONTAP in Azure with VM extensions causes delays in operations and NetApp recommends avoiding them.

== Flash Cache limitations
Cloud Volumes ONTAP uses the local NVMe storage in some VM types as _Flash Cache_. Note this limitation:

* Cache rewarming after a reboot is not supported.

== Limitations with high-availability deployments

High-availability (HA) pairs aren't supported in some regions.

https://bluexp.netapp.com/cloud-volumes-global-regions[View the list of supported Azure regions^].

== Limitations with HA deployments in single availability zones
Beginning with Cloud Volumes ONTAP 9.15.1, the deployment of virtual machine (VM) instances in HA mode in single availability zones (AZs) is possible in Azure. For information about the criteria supporting this feature, refer to https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure[Deploy HA pairs in single availability zones in Azure^].

If the Cloud Volumes ONTAP version is earlier than 9.15.1 or if any of these conditions are not met, the previous deployment model utilizing availability sets becomes effective. This applies to only HA configurations.

//https://jira.ngage.netapp.com/browse/BLUEXPDOC-373 
