---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.17.1 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.17.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.17.1 includes new enhancements.

Additional features and enhancements are also introduced in the latest version of the NetApp Console. For more information, see what's new in https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html[Cloud Volumes ONTAP^] managed in the Console.

== 9.17.1 P1 (04 November 2025)
The Cloud Volumes ONTAP 9.17.1 P1 patch is now available for deployment and upgrade in AWS, Azure, and Google Cloud. The Console will prompt you to upgrade your existing systems to this patch release.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P1[View the list of bugs fixed in the P1 patch^] (NetApp Support Site login required).

== 9.17.1 RC1 (4 September 2025)
You can now use the Release Candidate 1 of Cloud Volumes ONTAP 9.17.1 for deployment and upgrade in Azure and Google Cloud. However, this version is unavailable for deployment and upgrade in AWS.

//Update this section for every major release and every patch. This section can have a patch version as the first major release available for deployment and upgrade. Other patches might top this one. When 9.x.1 version of a 9.x.0 version is available, the patch rls for 9.x.0 stops: MM


== Upgrade notes

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from the Console. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when the Console notifies you^].

=== Supported upgrade path
You can upgrade to Cloud Volumes ONTAP 9.17.1 from the 9.16.1 release in AWS, Azure, and Google Cloud. For AWS, you can upgrade to Cloud Volumes ONTAP 9.17.1 P1 and later. The Console will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.


//Update this version for every major release. 9.x.0 v is can be usually upgraded from only the prev 9.x.1 version. But if the 9.x.0 version for a release has not gone, the n-2 for 9.x.1 will not be continued, and in that case only the previous 9.x.1 will be the upgrade path. The Console agent version removed as per code separation verification from engg: MM

=== Downtime

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is non-disruptive and I/O is uninterrupted. During this non-disruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

